# Generated by Django 5.1 on 2024-10-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_publication_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='content_media',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('gif', 'Gif')], max_length=10)),
                ('file', models.FileField(upload_to='publications/')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='api.publication')),
            ],
        ),
    ]
