# Generated by Django 5.1.1 on 2024-10-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_category'),
        ('api', '0015_remove_publication_content_media_media'),
    ]

    operations = [
    ]
