# Generated by Django 5.1 on 2024-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, default='group_images/default.png', null=True, upload_to='group_images/'),
        ),
    ]
