
FROM node:20


WORKDIR /app


RUN rm -rf node_modules && npm cache clean --force


COPY frontend/package.json frontend/package-lock.json /app/
RUN npm install --force


COPY frontend /app


RUN npm run build


EXPOSE 4173

CMD ["npm", "run", "preview", "--", "--host"]

