# Use an official Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY backend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY backend /app

# Expose port and run server
EXPOSE 8000
# CMD ["service", "postgresql", "start"]
CMD python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000