# Use an official Node.js image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY frontend/package.json frontend/package-lock.json /app/
RUN npm install

# Copy project files
COPY frontend /app

# Build the app for production
RUN npm run build

# Expose port and run server
EXPOSE 3000
CMD ["npm", "start"]
