# Use an official Node.js image
FROM node:20

# Set working directory
WORKDIR /app

# Clean up any previous node_modules and npm cache
RUN rm -rf node_modules && npm cache clean --force

# Install dependencies
COPY frontend/package.json frontend/package-lock.json /app/
RUN npm install --force

# Copy project files
COPY frontend /app

# Build the app for production
RUN npm run build

# Expose port and run server
EXPOSE 4173
# CMD ["npm", "start"]
CMD ["npm", "run", "preview", "--", "--host"]

