version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: money_tracker_user
      POSTGRES_PASSWORD: 1233den1233
      POSTGRES_DB: money_tracker_db
    ports:
      - "5432:5432"
