
FROM python:3.9-slim


WORKDIR /app


COPY backend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt


COPY backend /app


EXPOSE 8000

# CMD ["service", "postgresql", "start"]
CMD python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000

