from django.urls import path
from .views import (
    GroupCreatorCheckView, 
    GroupDataView,
    GroupCreatorGetView,
    ThreadCommentCountView,

    GroupCreateView, 
    GroupListView, 
    GroupMyListView,
    GroupUpdateView,
    GroupDeleteView,
    AssignModeratorView,
    AssignMemberView,
    BanUserView,
    UnbanUserView,
    ThreadCreateView,
    ThreadListView,
    ThreadUpdateView,
    ThreadDeleteView,
    ThreadDetailView,
    ThreadCommentCreateView,
    ThreadCommentListView,
    ThreadCommentDeleteView,
    ThreadCommentDetailView,
)

urlpatterns = [
    path('', GroupListView.as_view(), name='group_list'),  
    path('my/', GroupMyListView.as_view(), name='my_group_list'),  
    path('create/', GroupCreateView.as_view(), name='group_create'),  
    path('<int:group_id>/checkcreator/', GroupCreatorCheckView.as_view(), name='group_creator_check'),  
    path('<int:group_id>/getcreator/', GroupCreatorGetView.as_view(), name='group_creator_check'),  
    path('<int:group_id>/viewdata/', GroupDataView.as_view(), name='group_data'),  
    path('<int:pk>/update/', GroupUpdateView.as_view(), name='group_update'),
    path('<int:pk>/delete/', GroupDeleteView.as_view(), name='group_delete'),  
    path('<int:group_id>/assign_moderator/<int:user_id>/', AssignModeratorView.as_view(), name='assign_moderator'),
    path('<int:group_id>/assign_member/<int:user_id>/', AssignMemberView.as_view(), name='assign_member'),
    path('<int:group_id>/ban_user/<int:user_id>/', BanUserView.as_view(), name='ban_user'),
    path('<int:group_id>/unban_user/<int:user_id>/', UnbanUserView.as_view(), name='unban_user'),
    
    path('threads/create/', ThreadCreateView.as_view(), name='thread_create'),
    path('<int:group_id>/threads/', ThreadListView.as_view(), name='thread_list'),
    path('threads/<int:pk>/', ThreadUpdateView.as_view(), name='thread_update'),
    path('threads/<int:pk>/', ThreadDeleteView.as_view(), name='thread_delete'),
    path('threads/<int:pk>/', ThreadDetailView.as_view(), name='thread_detail'),
    path('threads_comments/<int:thread_id>/create/', ThreadCommentCreateView.as_view(), name='thread_comment_create'),
    path('threads_comments/<int:thread_id>/comments/', ThreadCommentListView.as_view(), name='thread_comment_list'),
    path('threads_comments/<int:thread_id>/commentscount/', ThreadCommentCountView.as_view(), name='thread_comment_list'),
    path('threads_comments/<int:pk>/delete/', ThreadCommentDeleteView.as_view(), name='thread-comment-delete'),
    path('threads_comments/<int:pk>/', ThreadCommentDetailView.as_view(), name='thread-comment-detail'),
]